[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.23.1"
tokio = { version = "1", features = ["full"] }
